<?php
return [
    'Dog' => [
        'Affenpinscher',
        'Afghan Hound',
        'Airedale Terrier',
        'Alaskan Malamute',
        'American Staffordshire Bull Terrier',
        'Anatolian Shepherd Dog',
        'Australian Cattle Dog',
        'Australian Kelpie',
        'Australian Shepherd Dog',
        'Australian Silky Terrier',
        'Australian Terrier',
        'Basenji',
        'Basset Fauve de Bretagne',
        'Basset Hound',
        'Beagle',
        'Bearded Collie',
        'Bedlington Terrier',
        'Belgian Shepherd Dog Groenendael',
        'Belgian Shepherd Dog Laekenois',
        'Belgian Shepherd Dog Malinois',
        'Belgian Shepherd Dog Tervueren',
        'Bernese Mountain Dog',
        'Bichon Frise',
        'Bloodhound',
        'Border Collie',
        'Border Terrier',
        'Borzoi',
        'Boston Terrier',
        'Bouvier des Flandres',
        'Boxer',
        'Bracco Italiano',
        'Briard',
        'Brittany',
        'Bull Terrier',
        'Bull Terrier Miniature',
        'Bulldog',
        'Bullmastiff',
        'Cairn Terrier',
        'Cavalier King Charles Spaniel',
        'Cesky Terrier',
        'Chesapeake Bay Retriever',
        'Chihuahua (Smooth Coat)',
        'Chinese Crested',
        'Chow Chow (Smooth)',
        'Clumber Spaniel',
        'Collie (Rough)',
        'Collie (Smooth)',
        'Curly-Coated Retriever',
        'Dachshund (Miniature Long Haired)',
        'Dachshund (Miniature Smooth Haired)',
        'Dachshund (Miniature Wire Haired)',
        'Dachshund (Smooth Haired)',
        'Dachshund (Wire Haired)',
        'Dalmatian',
        'Dandie Dinmont Terrier',
        'Deerhound',
        'Dobermann',
        'Dogue de Bordeaux',
        'English Setter',
        'English Springer Spaniel',
        'English Toy Terrier (Black & Tan)',
        'Field Spaniel',
        'Finnish Lapphund',
        'Finnish Spitz',
        'Flat-Coated Retriever',
        'Fox Terrier Smooth Coat',
        'Fox Terrier Wire Coat',
        'Foxhound',
        'French Bulldog',
        'German Shepherd Dog',
        'German Short-Haired Pointer',
        'German Spitz Klein',
        'German Wire-Haired Pointer',
        'Golden Retriever',
        'Gordon Setter',
        'Great Dane',
        'Greyhound',
        'Harrier Hound',
        'Hungarian Vizsla',
        'Hungarian Wire-Haired Vizsla',
        'Ibizan Hound',
        'Irish Setter',
        'Irish Terrier',
        'Irish Water Spaniel',
        'Irish Wolfhound',
        'Italian Greyhound',
        'Japanese Akita',
        'Japanese Chin',
        'Japanese Spitz',
        'Keeshond',
        'Kerry Blue Terrier',
        'King Charles Spaniel',
        'Labrador Retriever',
        'Lakeland Terrier',
        'Leonberger',
        'Lhaso Apso',
        'Lowchen',
        'Maltese',
        'Manchester Terrier',
        'Maremma Sheepdog',
        'Mastiff',
        'Newfoundland',
        'Norfolk Terrier',
        'Norwich Terrier',
        'Nova Scotia Duck Tolling Retriever',
        'Old English Sheepdog',
        'Papillon',
        'Parson Jack Russell Terrier',
        'Pharaoh Hound',
        'Pointer',
        'Pomeranian',
        'Poodle Miniature',
        'Poodle Standard',
        'Poodle Toy',
        'Portuguese Water Dog',
        'Pug',
        'Pyrenean Mountain Dog',
        'Rhodesian Ridgeback',
        'Rottweiler',
        'Saluki',
        'Samoyed',
        'Schipperke',
        'Schnauzer Giant',
        'Schnauzer Miniature',
        'Schnauzer Standard',
        'Scottish Terrier',
        'Shar Pei',
        'Shetland Sheepdog',
        'Shih Tzu',
        'Siberian Husky',
        'Skye Terrier',
        'Sloughi',
        'Soft Coated Wheaten Terrier',
        'St Bernard',
        'Sussex Spaniel',
        'Swedish Vallhund',
        'Tenterfield Terrier',
        'Tibetan Mastiff',
        'Tibetan Spaniel',
        'Tibetan Terrier',
        'Weimaraner',
        'Welsh Corgi (Cardigan)',
        'Welsh Corgi (Pembroke)',
        'Welsh Springer Spaniel',
        'Welsh Terrier',
        'West Highland White Terrier',
        'Whippet',
        'Yorkshire Terrier'
    ],

    'Cat' => [
        'Abyssinian',
        'Australian Mist',
        'Balinese',
        'Bengal',
        'Birman',
        'Bombay',
        'British Shorthair',
        'Burmese',
        'Burmilla',
        'Cornish Rex',
        'Devon Rex',
        'Egyptian Mau',
        'Exotic Shorthair',
        'Japanese Bobtail',
        'Korat',
        'La Perms',
        'Maine Coon',
        'Manx',
        'Norwegian Forest',
        'Ocicat',
        'Oriental Shorthair',
        'Persian Longhair',
        'Ragdoll',
        'Russian Blue',
        'Scottish Fold',
        'Siamese',
        'Siberian Forest',
        'Singapura',
        'Snowshoe',
        'Somali',
        'Sphynx',
        'Tiffanie',
        'Tonkinese',
        'Turkish Van'
    ],

    /*'rabbit' => [
        'Alaska',
        'Alexandria',
        'Altex',
        'American',
        'American Chinchilla', 
        'American Fuzzy Lop',
        'American Sable',
        'Angora',
        'APRI',
        'Argente Bleu',
        'Argente Brun',
        'Argente Clair',
        'Argente Creme',
        'Argente de Champagne',
        'Argente Noir',
        'Argente St Hubert',
        'Armenian Marder',
        'Astrex',
        'Baladi Black',
        'Baladi Red',
        'Baladi White',
        'Bauscat',
        'Beige',
        'Belgian Hare',
        'Beveren',
        'Big Silver Marten',
        'Blanc de Bouscat',
        'Blanc de Hotot',
        'Blanc de Popielno',
        'Blanc de Termonde',
        'Blue of Ham',
        'Blue of Sint-Niklaas',
        'Bourbonnais Grey',
        'Brazilian',
        'Britannia Petite',
        'British Giant',
        'Brown Chestnut of Lorraine',
        'Caldes',
        'Californian',
        'Canadian Plush Lop',
        'Carmagnola Grey',
        'Cashmere Lop',
        'Champagne d\'Argent', 
        'Chaudry',
        'Checkered Giant',
        'Chinchilla',
        'Chinchilla Giganta',
        'Cinnamon',
        'Continental Giant Coloured',
        'Continental Giant White',
        'Creme d\'Argent',
        'Criollo',
        'Cuban Brown',
        'Czech Red',
        'Czech Solver',
        'Czech Spot',
        'Czech White',
        'Dalmatian',
        'Deilenaar',
        'Dutch',
        'Dwarf Hotot',
        'Dwarf Lop',
        'Enderby Island',
        'English Angora',
        'English Lop',
        'English Spot',
        'Fauve de Bourgogne',
        'Flemish Giant',
        'Florida White',
        'Fox',
        'Fox–Silver',
        'French Angora',
        'French Lop',
        'Gabali',
        'German Angora',
        'German Lop',
        'Giant Angora',
        'Giant Chinchilla',
        'Giant Havana',
        'Giant Marburger',
        'Giant Papillon',
        'Giant Silver',
        'Giant Smoke Pearl',
        'Giza White',
        'Golden Glavcot',
        'Gotland',
        'Gouwenaar',
        'Grey Pearl of Halle',
        'Harlequin',
        'Harlequin Rex',
        'Havana',
        'Himalayan',
        'Holland Lop',
        'Hulstlander',
        'Hungarian Giant',
        'Isabella',
        'Jamora',
        'Japanese White',
        'Jersey Wooly',
        'Kabyle',
        'Lilac',
        'Lionhead',
        'Liptov Baldspotted Rabbit',
        'Lynx',
        'Marburger Feh',
        'Mecklenburger Piebald',
        'Meissner Lop',
        'Mellerud rabbit',
        'Mini Lop',
        'Mini Rex',
        'Mini Satin',
        'Miniature Cashmere Lop',
        'Miniature Lion Lop',
        'Miniature Lop',
        'Miniature Papillon',
        'Miniature Rex',
        'Miniature Satin',
        'Moshtohor',
        'Netherland Dwarf',
        'New Zealand',
        'New Zealand Red',
        'New Zealand White',
        'Nitransky',
        'Opossum',
        'Orange',
        'Palomino',
        'Pannon White',
        'Perlfee',
        'Plush Lop (Miniature)',
        'Plush Lop (Standard)',
        'Pointed Beveren',
        'Polish',
        'Rex',
        'Rhinelander',
        'Rhone',
        'Sachsengold',
        'Sallander',
        'San Juan',
        'Satin',
        'Satin Angora',
        'Schwarzgrannen',
        'Siamese Sable',
        'Siberian',
        'Silver',
        'Silver Fox',
        'Silver Marten',
        'Simenwar',
        'Slovenian Rabbit',
        'Smoke Pearl',
        'Spanish Giant',
        'Squirrel',
        'Standard Chinchilla',
        'Stone rabbit',
        'Sussex',
        'Swedish Fur',
        'Swedish Hare',
        'Swiss Fox',
        'Tadla',
        'Tan',
        'Teddy Dwarf',
        'Teddy Lop',
    ],*/
];
