<?php
return [
    'dog' => [
        'chihuahua',
        'dalmation',
        'minature_dachshund',
        'dachshund',
        'minature_poodle',
        'standard_poodle',
        'rockweiler',
        'british_bulldog',
        'border_collie',
        'german_shepard',
        'greyhound',
        'mastiff',
        'golden_retriever',
        'labrador',
        'labradoodle',
        'irish_terrier',
        'scottish_terrier',
        'welsh_terrier',
        'airedale',
        'basset_hound',
        'bichon_frise',
        'saint_bernard',
        'akita',
        'pitbull',
        'afghan_hound',
        'beagle',
        'corgi',
    ],

    'cat' => [
        'russian_blue',
        'persian_cat',
        'scottish_fold',
        'british_shorthair',
        'siamese_cat',
        'maine_coon',
        'munchkin_cat',
        'bengal_cat',
        'turkish_angora',
        'norwegian_forest_cat',
        'savannah_cat',
    ],

    'bird' => [],
    'fish' => [],
    'hamster' => [],
    'rabbit' => [],
    'horse' => [],
];
